// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgmzptJ3Fv0sg7skN6CqudobTFlY6Zdug',
    appId: '1:1059218786957:web:63850b716cd3f7d0e670c4',
    messagingSenderId: '1059218786957',
    projectId: 'socialmedia-b8628',
    authDomain: 'socialmedia-b8628.firebaseapp.com',
    storageBucket: 'socialmedia-b8628.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv2IqqGQXjUMXC6PDykycP7qouKvL6SzU',
    appId: '1:1059218786957:android:fd9853ccd8f8da7de670c4',
    messagingSenderId: '1059218786957',
    projectId: 'socialmedia-b8628',
    storageBucket: 'socialmedia-b8628.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7F9SNiX6CMILqcKTb1MFyyjgAXpxgUdc',
    appId: '1:1059218786957:ios:8f0d534c094bef57e670c4',
    messagingSenderId: '1059218786957',
    projectId: 'socialmedia-b8628',
    storageBucket: 'socialmedia-b8628.appspot.com',
    iosBundleId: 'com.example.socialmedia',
  );
}
